import { IProjectCard } from "../models/project-card";

export const StaticProjectCards: IProjectCard[] = [
  {
    repo: {
      name: "ATLAS",
      full_name: "UniversalLogistics/ATLAS",
      description: "A suite of ERP applications and repositories focused on managing the business of Universal Logistics Holdings. A summary of their business entails invoicing customers, dispatching drivers, and paying parties involved. Highlights of my work include re-architecting their settlements system, creating automated SQL migration deployments, standardizing common systems, and being a part of their tech debt work force",
      owner: {
        login: "UniversalLogistics",
        avatar_url: "",
        url: "",
        html_url: "",
      },
      fork: false,
      private: true,
      topics: [
        "full-stack",
        "front-end",
        "back-end",
        "microservices",
        "mvc",
        "domain-driven-design",
        "sql-kata",
        "sql-server",
        "entity-framework",
        "asp.net",
        "dotnet-6",
        "dotnet-core",
        "storybook",
        "angular",
        "tailwindcss",
        "angular-material",
        "nunit",
        "unit-testing",
        "devops",
        "gocd",
        "automated-deployment",
        "docker",
        "",
      ],
      stargazers_count: 0,
      watchers_count: 0,
      open_issues_count: 0,
      html_url: "",
      languages_url: "",
      contributors_url: "",
      license: "",
      created_at: "",
      updated_at: "",
      pushed_at: "",
    },
    languages: {
      "HTML": 1,
      "TypeScript": 1,
      "SCSS": 1,
      "C#": 1,
      "SQL": 1,
      "Python": 1,
      "Dockerfile": 1,
      "Shell": 1,
      "Powershell": 1,
    },
    contributors: [{
      "login": "Xerner",
      "id": 48263885,
      "node_id": "MDQ6VXNlcjQ4MjYzODg1",
      "avatar_url": "https://avatars.githubusercontent.com/u/48263885?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Xerner",
      "html_url": "https://github.com/Xerner",
      "followers_url": "https://api.github.com/users/Xerner/followers",
      "following_url": "https://api.github.com/users/Xerner/following{/other_user}",
      "gists_url": "https://api.github.com/users/Xerner/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Xerner/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Xerner/subscriptions",
      "organizations_url": "https://api.github.com/users/Xerner/orgs",
      "repos_url": "https://api.github.com/users/Xerner/repos",
      "events_url": "https://api.github.com/users/Xerner/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Xerner/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 0
    }]
  }
]
